version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:2.176.2
    container_name: jenkins
    volumes:
      - /local_app/docker-swarm-jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
